### ISSUE TITLE
Choice to select subkeys to export

### ISSUE THREAD

**Issue by SaptakS** [kushaldas/tumpa#10]
Suggestion: It would be good to have an options to give users the choice to select which subkeys they want to write on the smartcard

Note: In a way, we can give a similar option while generation as well if someone wants to skip creating certain subkey (authentication key for example)

**Comment by kushaldas** [comment]
Figuring out which subkeys to generate is now done at #11

**Comment by SaptakS** [comment]
Resolved in #11  and #12
