### ISSUE TITLE
Show card details in UI somewhere

### ISSUE THREAD

**Issue by kushaldas** [kushaldas/tumpa#37]
Many users asked for an option to see the details of the connected smartcard in UI.

**Comment by kushaldas** [comment]
Maybe I can I figure out the APDUs for Yubikey to find out what kind of Yubikey is attached.

**Comment by krihal** [comment]
This commit [1] implements a statusbar which shows the serial number of the Yubikey. If johnnycanencrypt can be extended with fetching information about Yubikey version etc it can easily be added to the statusbar.

1: https://github.com/krihal/tumpa/commit/27f6d83ba5e7ad795b30bf425ee8f090eb92130b

**Comment by krihal** [comment]
https://github.com/kushaldas/tumpa/pull/45

**Comment by SaptakS** [comment]
@kushaldas this has been implemented in https://github.com/kushaldas/tumpa/issues/57. Closing.
